include:
  - project: 'csirt-mu-analytics/analytics-artifacts'
    ref: 'master'
    file: 'ci-templates/base.gitlab-ci.yml'

.venv:
  image: python:3.12
  before_script:
    - pip install uv
    - uv sync --frozen --all-extras
    - source .venv/bin/activate

lint:
  stage: test
  extends: .venv
  script:
    - pre-commit run --all-files

build:
  extends: .venv
  script:
    - uv build
  artifacts:
    paths:
      - build/*
