repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: check-case-conflict
  - id: check-illegal-windows-names
  - id: check-merge-conflict
  - id: check-toml
  - id: end-of-file-fixer
  - id: fix-byte-order-marker
  - id: trailing-whitespace
- repo: https://github.com/codespell-project/codespell
  rev: v2.4.1
  hooks:
  - id: codespell
- repo: https://github.com/executablebooks/mdformat
  rev: 0.7.22
  hooks:
    - id: mdformat
      args:
      - --check
- repo: https://github.com/DetachHead/basedpyright-pre-commit-mirror
  rev: 1.27.1
  hooks:
  - id: basedpyright
    args:
    - --venvpath=.
    - --level=error  # suppress warnings
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.9.6
  hooks:
  - id: ruff
    args:
    - --ignore=FIX  # TODO/FIXME comments
  - id: ruff-format
    args:
    - --check
