[project]
name = "service-connectors-v2"
dynamic = ["version"]
description = ""
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "certifi>=2025.1.31",
    "pydantic>=2.11.7",
]

[project.optional-dependencies]
trino = [
    "trino>=0.333.0",
]
intelowl = [
    "pyintelowl>=5.1.0",
]
http = [
    "aiohttp>=3.13.3",
]

[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "dacite>=1.9.2",
    "pre-commit>=4.1.0",
    "pytest>=8.3.4",
    "pytest-asyncio>=0.25.3",
    "python-dotenv>=1.0.1",
]

[tool.basedpyright]
venv = ".venv"  # needed for pre-commit hook

[tool.codespell]
ignore-words = ".codespell-whitelist.txt"

[tool.hatch]
# Moved to => hatch.toml

[tool.pytest]
pythonpath = ["src"]
norecursedirs = ["tests/utils"]
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "module"
asyncio_default_test_loop_scope = "module"

[tool.ruff]
# Moved to => ruff.toml
